### ISSUE TITLE
[SINATRAAPP] Implement log-in functionality

### ISSUE THREAD

**Issue by recrudescence** [lmilekic/bluejadetwitter#1]
##### [SINATRAAPP] nanoTwitter version 0.1: Implement Sinatra front end application for ui.

> _Use ActiveRecord and Sqlite3 for development (local) db. You will use the sketches from [HTMLUI] to implement .html.erb files that in a view directory to display the views. Later when you deploy to heroku you will enable Postgress for your production (heroku) db. You should have all the functionality working described as “nT User Interface” in nano Twitter Functionality_
### Login functionality

Inputting username and password should log you in. This will probably consist of a GET for username/password and cross-checking, then a POST or a PUT or something to update logged-in status field to true.

**Comment by lmilekic** [comment]
Does this include other pages changing based on logged in/not logged in status? Or is that a whole different story?

**Comment by recrudescence** [comment]
do we need a logged-in field if we have sessions now? wait why do we even need logged-in in the first place (was it bc of those 'other pages' changing based on logged-in status)

should we remove logged-in from User?
