### ISSUE TITLE
[misc] Fix site navigation

### ISSUE THREAD

**Issue by cjnice** [lmilekic/bluejadetwitter#19]
You should be able to go from homepage to your profile and vice versa

**Comment by lmilekic** [comment]
oh shit, didn't realize only one person can be assigned to stuff. I was just gonna add minimal links in the basic layout.erb file.

**Comment by lmilekic** [comment]
Passing it back off to calvin to make it pretty

**Comment by cjnice** [comment]
the ui.clara.34 branch has a pretty and working version of the welcome page, calvin if you wanna take a look

**Comment by recrudescence** [comment]
clicking your name on your homepage now goes to your profile~
