### ISSUE TITLE
[API] Implement API -- return JSON

### ISSUE THREAD

**Issue by recrudescence** [lmilekic/bluejadetwitter#47]
Visiting a specific page should return JSON:

**REST-y API**
/api/v1/tweets/23 - return tweet with id
/api/v1/users/23 - return user information for user 23
/api/v1/tweets/recent - return the recent n tweets
/api/v1/users/23/tweets - return the users recent tweets

**Values as JSON**
Tweet: { "id": 123, "text": foobar, "created": jan-11-2015 }
User: {"id": name": Pito Salas}
List of tweets: [<tweet>, <tweet>,...]
Follow list: ["user_id": 22, "user_id": 23, ...]

**Comment by recrudescence** [comment]
[via this post](https://nathanhoad.net/how-to-return-json-from-sinatra)

> It's so easy to output JSON from Sinatra it will take longer to read this post than to actually do it.
> 
> First, make sure you have the 'json' gem:
> `sudo gem install json`
> Then require it in your Sinatra application:
> `require 'json'`
> 
> Now all you have to do is spit out some JSON using the to_json method provided by the gem. Here is a simple example to try it out:
> 
> ```
> get '/example.json' do
>   content_type :json
>   { :key1 => 'value1', :key2 => 'value2' }.to_json
> end
> ```
> 
> It's that simple.

**Comment by lmilekic** [comment]
Sorry, didn't realize you were still working on it. Seems like you've either got the whole thing working or nearly.

**Comment by recrudescence** [comment]
almost done! finishing up tests
