### ISSUE TITLE
[specialtest] Create special user and related functionality

### ISSUE THREAD

**Issue by recrudescence** [lmilekic/bluejadetwitter#78]
his name shall be pitobread

**Comment by lmilekic** [comment]
goddamn, I was just typing this thing in when I got the email

**Comment by recrudescence** [comment]
some specific url that will do this: `bluejade.heroku.com/test_tweet`
special url that deletes: `bluejade.heroku.com/test_follow`
special url that deletes all tweets and follows by user: `/reset`

**Comment by recrudescence** [comment]
should be something like

```
get '/url' do
  tweet.create( id = pitobread's id, tweet text is faker.randomsmartthing, etc.
  if tweet then tweet.save etc etc
end
```

**Comment by cjnice** [comment]
Nick's Notes:
1. 100 most recent tweets on homepage
2. /test_tweet
       - Alternate posting tweets and reloading home page (check caching and fast update)
   - Create User
   - Create URL that posts a random tweet by test_user
   - Load the homepage to see updated list of most recent tweets
   - Special URL that deletes all of the data (for convenience)
3. /test_follow
   - Create URL that causes testuser to follow/unfollow user
   - Load test_user profile page (100 most recent tweets by people she follows)
4. /reset
   - Delete all of test_user's
   - test_user unfollows everyone
