### ISSUE TITLE
[FINALDELIVERABLE] Portfolio Page

### ISSUE THREAD

**Issue by recrudescence** [lmilekic/bluejadetwitter#95]
Clara's already got the ball rolling with http://bluejade.strikingly.com/ ! Now to finish it:

Make it look pretty!
- 2 page web site
- An “e-brochure” for your project
- Containing info such as:
  - Summary statement of assignment (1-2 paragraphs)
  - Screenshots
  - Technology Description
  - Interesting Engineering
  - Result of scalability work, timings etc.
  - Team members
  - Dates

**Comment by zhogan18** [comment]
How do we get access to edit it?

**Comment by recrudescence** [comment]
@cjnice has the login deets! can you post it on slack?
